# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{howl}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Clinton R. Nixon"]
  s.date = %q{2010-10-23}
  s.default_executable = %q{howl}
  s.description = %q{Howl is a tiny static website/blog generator.}
  s.email = %q{crnixon@gmail.com}
  s.executables = ["howl"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/howl",
     "howl.gemspec",
     "lib/howl.rb",
     "lib/howl/converter.rb",
     "lib/howl/converters/markdown.rb",
     "lib/howl/converters/sass.rb",
     "lib/howl/core_ext.rb",
     "lib/howl/generator.rb",
     "lib/howl/page.rb",
     "lib/howl/plugin.rb",
     "lib/howl/post.rb",
     "lib/howl/sample_site/.gitignore",
     "lib/howl/sample_site/Rakefile",
     "lib/howl/sample_site/config.yml",
     "lib/howl/sample_site/posts/first_post.md",
     "lib/howl/sample_site/site/css/screen.scss",
     "lib/howl/sample_site/site/index.html",
     "lib/howl/sample_site/templates/default.html",
     "lib/howl/sample_site/templates/post.html",
     "lib/howl/sample_site/templates/site.html",
     "lib/howl/site.rb",
     "lib/howl/template.rb",
     "lib/howl/view.rb",
     "test/fixtures/config.yml",
     "test/fixtures/posts/first_post.html",
     "test/fixtures/posts/markdown_post.md",
     "test/fixtures/posts/no_date.html",
     "test/fixtures/site/css/modules/colors.scss",
     "test/fixtures/site/css/screen.scss",
     "test/fixtures/site/empty.html",
     "test/fixtures/site/has_template.html",
     "test/fixtures/site/index.html",
     "test/fixtures/site/no_yaml.html",
     "test/fixtures/site/simple.html",
     "test/fixtures/templates/alt.html",
     "test/fixtures/templates/default.html",
     "test/fixtures/templates/post.html",
     "test/fixtures/templates/site.html",
     "test/howl_test.rb",
     "test/integration_site/config.yml",
     "test/integration_site/posts/post.md",
     "test/integration_site/site/images/logo.png",
     "test/integration_site/site/index.html",
     "test/integration_site/site/stylesheets/screen.css",
     "test/integration_site/templates/post.html",
     "test/integration_site/templates/site.html",
     "test/integration_test.rb",
     "test/teststrap.rb"
  ]
  s.homepage = %q{http://github.com/crnixon/howl}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A tiny static website/blog generator.}
  s.test_files = [
    "test/howl_test.rb",
     "test/integration_test.rb",
     "test/teststrap.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<riot>, [">= 0.11"])
      s.add_development_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<rdiscount>, [">= 0"])
      s.add_runtime_dependency(%q<mustache>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
    else
      s.add_dependency(%q<riot>, [">= 0.11"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rdiscount>, [">= 0"])
      s.add_dependency(%q<mustache>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
    end
  else
    s.add_dependency(%q<riot>, [">= 0.11"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rdiscount>, [">= 0"])
    s.add_dependency(%q<mustache>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
  end
end

